stages:
- name: Gerar imagem
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: teste-deploy:5
<<<<<<< HEAD
      pushRemote: true
=======
>>>>>>> 3cb08e5c023e2efc1a2f2a946e4ca9d3ca92a08c
      registry: 10.90.2.77:5000
      pushRemote: true
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
