stages:
- name: Gerar imagem
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: deploy-sb:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34724
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
