stages:
- name: Gerar imagem
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: teste-deploy:${CICD_EXECUTION_SEQUENCE}
      registry: http://10.90.2.77:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
