stages:
- name: Gerar imagem
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      #      tag: 546058309270.dkr.ecr.us-east-1.amazonaws.com/deploy-sb:${CICD_EXECUTION_SEQUENCE}
      tag: deploy-sb:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      #     registry: 546058309270.dkr.ecr.us-east-1.amazonaws.com/deploy-sb
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
