stages:
- name: Gerar imagem
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cezarfw/deploysb:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
