stages:
- name: Gerar imagem
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: deploy-SBteste:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
