apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: site
  namespace: site
  labels: 
    workload.user.cattle.io/workloadselector: deployment-site-site
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-site-site
  template:
    metadata:
      labels:
        app: site
        workload.user.cattle.io/workloadselector: deployment-site-site
    spec:
      containers:
        - name: site
          image: 546058309270.dkr.ecr.us-east-1.amazonaws.com/deploy-sb:${CICD_EXECUTION_SEQUENCE}
          ports:
          - containerPort: 80 
