apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: fiserv-prod
  labels: 
    workload.user.cattle.io/workloadselector: deployment-fiserv-prod-site
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-fiserv-prod-site
  template:
    metadata:
      labels:
        app: site
        workload.user.cattle.io/workloadselector: deployment-fiserv-prod-site
    spec:
      containers:
        - name: site
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
          - containerPort: 80 
