apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-btdmw
    field.cattle.io/publicEndpoints: '[{"addresses":["10.90.2.76"],"port":80,"protocol":"HTTP","serviceName":"default:ingress-c7e3ba6e2b7449d8cd3ecb9a9c058df0","ingressName":"default:site-teste","hostname":"site-teste.default.10.90.2.76.xip.io","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
     {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2","field.cattle.io/creatorId":"user-btdmw","field.cattle.io/publicEndpoints":"[{\"addresses\":[\"10.90.2.76\"],\"port\":80,\"protocol\":\"HTTP\",\"serviceName\":\"default:ingress-c7e3ba6e2b7449d8cd3ecb9a9c058df0\",\"ingressName\":\"default:site-teste\",\"hostname\":\"site-teste.default.10.90.2.76.xip.io\",\"allNodes\":true}]"},"generation":3,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-default-nginx"},"name":"nginx","namespace":"default","resourceVersion":"3582975","selfLink":"/apis/apps/v1beta2/namespaces/default/deployments/nginx","uid":"aa297db2-264c-11e9-89e2-08002775e2b0"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-default-nginx"}},"template":{"metadata":{"labels":{"app":"nginx","workload.user.cattle.io/workloadselector":"deployment-default-nginx"}},"spec":{"containers":[{"image":"10.90.2.77:5000/novonginx","imagePullPolicy":"Always","name":"nginx","resources":{},"tty":true}]}}}}
#  creationTimestamp: 2019-02-01T18:10:32Z
  generation: 4
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-nginx
  name: nginx
  namespace: default
#  resourceVersion: "3592094"
#  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/nginx
#  uid: aa297db2-264c-11e9-89e2-08002775e2b0
spec:
#  progressDeadlineSeconds: 600
#  replicas: 1
#  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-nginx
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
#      creationTimestamp: null
      labels:
        app: nginx
        workload.user.cattle.io/workloadselector: deployment-default-nginx
    spec:
      containers:
      - image: 10.90.2.77:5000/novonginx:latest
        imagePullPolicy: Always
        name: nginx
#        resources: {}
#        securityContext:
#          allowPrivilegeEscalation: false
#          capabilities: {}
#          privileged: false
#          readOnlyRootFilesystem: false
#          runAsNonRoot: false
#        stdin: true
#        terminationMessagePath: /dev/termination-log
#        terminationMessagePolicy: File
        tty: true
#      dnsPolicy: ClusterFirst
#      restartPolicy: Always
#      schedulerName: default-scheduler
#      securityContext: {}
#      terminationGracePeriodSeconds: 30

